"""Generate a config/accounts.yaml stub from account_ids seen in the archive.

account_owner is null in Plaid data, so the human supplies person/name/include
(PLAN.md §8, §15). This only scaffolds the keys; it never overwrites an existing
file (your hand-entered mapping is precious).

Usage:
    python -m tools.gen_accounts [--app config/app.yaml]
"""
from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config_io import PERSONAL_CONFIG_DIR, load_app_config  # noqa: E402
from ingest import ingest  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
# accounts.yaml is personal data: it lives under the external data root.
ACCOUNTS = PERSONAL_CONFIG_DIR / "accounts.yaml"


def _archive_paths(app_path: Path) -> list[str]:
    # Reuse config_io's resolution (relative paths resolve from the data root).
    return load_app_config(app_path).resolved_archive_paths


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--app", default=str(ROOT / "config" / "app.yaml"))
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    if ACCOUNTS.exists() and not args.force:
        print(f"refusing to overwrite {ACCOUNTS} (use --force)", file=sys.stderr)
        return 1

    res = ingest(_archive_paths(Path(args.app)))
    counts = Counter(t.account_id for t in res.transactions)
    # The collector stamps txn_owner per record; an account's stamp seeds `person`.
    owners = {t.account_id: t.owner for t in res.transactions if t.owner}

    lines = [
        "# accounts.yaml — account_id -> person + friendly name + include?",
        "# `person` is seeded from the records' txn_owner stamp where present;",
        "# the other fields are unknowable from the archive, so fill them in by hand.",
        "# Set include: false to drop an account entirely from analysis.",
        "#",
        "# Generated by `python -m tools.gen_accounts`. Safe to edit; not overwritten.",
        "accounts:",
    ]
    for acct_id, n in counts.most_common():
        lines.append(f"  {acct_id}:")
        lines.append(f"    person: {owners.get(acct_id, 'Unknown')}")
        lines.append("    name: Unnamed account")
        lines.append("    type: depository      # depository | credit | loan | investment")
        lines.append("    subtype: checking")
        lines.append("    institution: Unknown")
        lines.append("    include: true")
        lines.append(f"    # {n} transactions in current archive")
    ACCOUNTS.parent.mkdir(parents=True, exist_ok=True)
    ACCOUNTS.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {ACCOUNTS} ({len(counts)} accounts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
