"""Generate config/taxonomy.yaml from the embedded PFC taxonomy.

Bootstrap so no one hand-writes ~104 rows (PLAN.md §6.6). Editing the result
never recategorizes transactions — atoms are stable; only the rollup changes.

Usage:
    python -m tools.gen_taxonomy [--force]

Refuses to clobber an existing, hand-tuned file unless --force is given.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# allow running as a script
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tools.pfc_taxonomy import DETAILED, atom_tiers, all_atoms  # noqa: E402

CONFIG = Path(__file__).resolve().parent.parent / "config" / "taxonomy.yaml"

HEADER = """# taxonomy.yaml — atoms -> category tiers, merchant overrides, exclusions.
#
# AUTO-GENERATED by `python -m tools.gen_taxonomy` from the embedded Plaid PFC
# taxonomy, then hand-tuned. Atoms are the stable leaf (PFC `detailed`, ~104
# values). Editing tiers here NEVER recategorizes data — only the rollup changes.
#
# Strict nesting rule (PLAN.md §6.3): every atom maps to exactly one
# tier2 -> tier1 -> tier0(necessity). Keep it nested so rollups never double-count.
#
# Do NOT bake geo / recurrence / channel / person into this tree — those are
# first-class FACETS composed on demand by the renderer (PLAN.md §6.5).
"""


def build_yaml() -> str:
    lines: list[str] = [HEADER]

    # --- exclusions: internal money movement (the #1 double-count trap) ---
    lines.append("# Internal money movement: excluded from spend/income aggregates.")
    lines.append("# KEEP LOAN_PAYMENTS_MORTGAGE_PAYMENT — that is real spend.")
    lines.append("exclude_detailed:")
    for pat in ("TRANSFER_IN_*", "TRANSFER_OUT_*", "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT"):
        lines.append(f"  - {pat}")
    lines.append("")

    # --- atoms ---
    lines.append("atoms:")
    for primary in DETAILED:
        lines.append(f"  # --- {primary} ---")
        for detailed in DETAILED[primary]:
            tier0, tier1, tier2 = atom_tiers(detailed, primary)
            lines.append(
                f"  {detailed}: {{tier0: {tier0}, tier1: {tier1!r}, tier2: {tier2!r}}}"
            )
        lines.append("")

    # --- merchant overrides (starter) ---
    lines.append("# Merchant overrides: regex on merchant_name OR exact merchant_entity_id.")
    lines.append("# Example splits 'Uber Eats' (food) from 'Uber' (rideshare).")
    lines.append("merchant_overrides:")
    lines.append("  '(?i)uber\\s*eats': {tier1: 'Dining Out', tier2: 'Restaurant'}")
    lines.append("  '(?i)doordash|grubhub': {tier1: 'Dining Out', tier2: 'Restaurant'}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--force", action="store_true", help="overwrite existing file")
    args = ap.parse_args()

    CONFIG.parent.mkdir(parents=True, exist_ok=True)
    if CONFIG.exists() and not args.force:
        print(f"refusing to overwrite {CONFIG} (use --force)", file=sys.stderr)
        return 1
    CONFIG.write_text(build_yaml(), encoding="utf-8")
    n = len(all_atoms())
    print(f"wrote {CONFIG} ({n} atoms)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
